name: Build Dockerfile
on: [workflow_dispatch]

jobs:

  Build-Image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker build ./ --tag ghcr.io/ascot4fusion/ascot5deps:latest
          docker run ghcr.io/ascot4fusion/ascot5deps:latest
          docker push ghcr.io/ascot4fusion/ascot5deps:latest
